# Generated by Django 4.2.2 on 2023-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_shoppinglist_remove_shoppingrecipelist_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredient', through='recipes.RecipeIngredient', to='recipes.ingredientamaunt'),
        ),
    ]
