# Generated by Django 4.2.2 on 2023-06-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmaunt',
            new_name='IngredientAmount',
        ),
    ]
